# Generated by Django 4.0.4 on 2022-05-17 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_crrent_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='crrent_song',
            new_name='current_song',
        ),
    ]
